image: registry.gitlab.com/metalibm-dev/pythonsollya:ci

before_script:

valid_python2:
    script:
        - export LD_LIBRARY_PATH=/usr/local/lib # exposing libsollya.so
        - export PYTHON=python2
        - make install # building and installing pythonsollya
        - make test # testing pythonsollya

