image: registry.gitlab.com/metalibm-dev/pythonsollya:ci_sollya_master_21.09

before_script:
    - export LD_LIBRARY_PATH=/usr/local/lib # exposing libsollya.so
    - python3.8 -m pip install bigfloat # provide python's mpfr module

valid_python3.8:
    script:
        - git clone https://gitlab.inria.fr/sollya/sollya.git -b master sollya_git
        - cd sollya_git && sh autogen.sh && ./configure && make && make install && cd ..
        - export LD_LIBRARY_PATH=/usr/local/lib  # exposing libsollya.so
        - export PYTHON=python3.8
        - export PIP=pip3
        - export WITH_EXTERNALDATA=yes
        - make install SOLLYA_DIR=/usr/local/ # building and installing pythonsollya
        - make test SOLLYA_DIR=/usr/local/ # testing pythonsollya


