image: registry.gitlab.com/metalibm-dev/pythonsollya:ci_sollya_master

before_script:
    - git clone https://scm.gforge.inria.fr/anonscm/git/sollya/sollya.git -b master sollya_git
    - cd sollya_git && sh autogen.sh && ./configure && make && make install && cd ..
    - export LD_LIBRARY_PATH=/usr/local/lib # exposing libsollya.so

valid_python2:
    script:
        - export PYTHON=python2
        - make install # building and installing pythonsollya
        - make test # testing pythonsollya

valid_python3:
    script:
        - export PYTHON=python3
        - make install # building and installing pythonsollya
        - make test # testing pythonsollya
