image: registry.gitlab.com/metalibm-dev/pythonsollya:ci

before_script:
    - export LD_LIBRARY_PATH=/usr/local/lib # exposing libsollya.so

valid_python2:
    script:
        - export PYTHON=python2
        - make build   # building pythonsollya
        - make install # building and installing pythonsollya
        - make test # testing pythonsollya

valid_python3:
    script:
        - export PYTHON=python3
        - make build   # building pythonsollya
        - make install #  installing pythonsollya
        - make test # testing pythonsollya
